# Generated by Django 4.2.1 on 2023-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Eメールアドレス')),
                ('account_name', models.CharField(max_length=50, null=True, unique=True, verbose_name='アカウント名')),
                ('last_name', models.CharField(default='law', max_length=30, verbose_name='姓')),
                ('first_name', models.CharField(default='Out', max_length=30, verbose_name='名')),
                ('profile_image', models.ImageField(default='default_image.jpg', upload_to='profile_images/', verbose_name='アカウント画像')),
                ('country', models.CharField(default='Outlaw', max_length=50, verbose_name='在住国')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
