# Generated by Django 4.2.1 on 2023-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/static/default_images/default_plofile.png', upload_to='media_local/profile_images', verbose_name='アカウント画像'),
        ),
    ]
