# Generated by Django 4.2.1 on 2023-07-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_name',
            new_name='username',
        ),
    ]
