# Generated by Django 4.2.1 on 2023-07-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_username_user_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
