# Generated by Django 4.2.3 on 2023-07-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_country_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_images/default_profile.png', null=True, upload_to='profile_images'),
        ),
    ]
