FROM python:3 
ENV PYTHONUNBUFFERED 1 
RUN pip install django
RUN pip install django-allauth
#フォームに対して自動でBootstrapクラスを適用してくれるモジュール
RUN pip install django-crispy-forms
RUN pip install django-bootstrap4

