# Generated by Django 4.2.1 on 2023-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('applying', '申請中'), ('joined', '参加済み')], default='not_participating', max_length=20),
        ),
    ]
