# Generated by Django 4.2.3 on 2023-07-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_kind',
            field=models.CharField(choices=[('Web', 'Web'), ('Software', 'Software'), ('Mobile App', 'Mobile App'), ('Data Science', 'Data Science'), ('Game Development', 'Game Development'), ('Blockchain', 'Blockchain'), ('IoT', 'Internet of Things'), ('AR/VR', 'Augmented Reality/Virtual Reality'), ('E-commerce', 'E-commerce'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Food and Beverage', 'Food and Beverage'), ('Music', 'Music'), ('Art and Design', 'Art and Design')], max_length=50),
        ),
    ]
