# Generated by Django 4.2.1 on 2023-05-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='is_completed_taskmember',
            new_name='is_completed_member',
        ),
        migrations.AlterField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projectManagement.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projectManagement.unit'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projectManagement.task'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projectManagement.phase'),
        ),
    ]
