# Generated by Django 4.2.3 on 2023-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_alter_project_project_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_color',
            field=models.CharField(default='#342186', max_length=7),
        ),
    ]
