# Generated by Django 4.2.1 on 2023-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_projectmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Middle'), (3, 'Low')], default=2),
        ),
    ]
