# Generated by Django 4.2.3 on 2023-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0003_project_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_color',
            field=models.CharField(default='#342186', max_length=7, null=True),
        ),
    ]
