# Generated by Django 4.2.1 on 2023-07-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0003_alter_project_project_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectManagement.projectmember'),
        ),
    ]
