# Generated by Django 4.2.1 on 2023-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0003_alter_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dead_line',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
