# Generated by Django 4.2.1 on 2023-07-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0005_remove_task_task_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.AddField(
            model_name='phase',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.projectmember'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.projectmember'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_kind',
            field=models.CharField(choices=[('Web', 'Web'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('test', 'test')], max_length=50),
        ),
    ]
